import type { DocumentHistoryCommand } from './types'

const actionLabels: Record<DocumentHistoryCommand['actionType'], string> = {
  'set-bit-depth': 'Change document precision',
  'set-canvas-preset': 'Change canvas preset',
  'set-canvas-size': 'Resize canvas',
  'set-background': 'Change background',
  'set-pattern': 'Change pattern',
  'set-channels': 'Edit channels',
  'set-paths': 'Edit paths',
  'set-guides': 'Edit guides',
  'set-grid': 'Change grid',
  'set-artboards': 'Edit artboards',
  'set-color-mode': 'Change color mode',
  'set-color-settings': 'Change color management',
  'set-animation': 'Edit animation',
  'set-slices': 'Edit export slices',
  'set-file-metadata': 'Edit file metadata',
  'set-print-settings': 'Change print setup',
  'set-measurements': 'Edit measurement log',
  'set-measurement-scale': 'Calibrate measurements',
  'set-color-samplers': 'Edit color samplers',
  'set-counts': 'Edit count records',
  'set-notes': 'Edit annotations',
  'replace-document': 'Replace document',
  'add-layer': 'Add layer',
  'replace-layer': 'Rasterize layer',
  'add-group': 'Add layer group',
  'update-layer': 'Edit layer',
  'update-layers': 'Edit layers',
  'update-group': 'Edit layer group',
  'remove-layer': 'Delete layer',
  'remove-layers': 'Delete layers',
  'remove-group': 'Delete layer group',
  'select-layer': 'Select layer',
  'select-group': 'Select layer group',
  'move-layer': 'Move layer',
  'move-group': 'Move layer group',
  'move-stack-item': 'Reorder layers',
  'reset-document': 'Reset document',
}

export function historyCommandLabel(command: DocumentHistoryCommand) {
  return actionLabels[command.actionType]
}
