import { useState } from 'react'
import type { AdjustmentCmyk, AdjustmentDescriptor, AdjustmentLevelsChannel, AdjustmentMixerChannel } from '../editor/types'
import { RangeControl } from './Control'

type Props = { adjustment: AdjustmentDescriptor; layerId: string; onChange: (patch: Record<string, unknown>, groupKey?: string) => void; onChangeEnd: () => void }
const fieldClass = 'w-full rounded border border-white/[0.08] bg-zinc-950 px-2 py-1.5 text-[9px] text-zinc-400 outline-none'
const levelsDefault: AdjustmentLevelsChannel = { shadowInput: 0, highlightInput: 255, shadowOutput: 0, highlightOutput: 255, midtoneInput: 1 }
const cmykDefault: AdjustmentCmyk = { c: 0, m: 0, y: 0, k: 0 }
const mixerDefault: AdjustmentMixerChannel = { red: 0, green: 0, blue: 0, constant: 0 }

export function AdvancedAdjustmentControls({ adjustment, layerId, onChange, onChangeEnd }: Props) {
  const [levelsChannel, setLevelsChannel] = useState<'rgb' | 'red' | 'green' | 'blue'>('rgb')
  const [selectiveRange, setSelectiveRange] = useState<'reds' | 'yellows' | 'greens' | 'cyans' | 'blues' | 'magentas' | 'whites' | 'neutrals' | 'blacks'>('neutrals')
  const [mixerOutput, setMixerOutput] = useState<'red' | 'green' | 'blue'>('red')

  if (adjustment.type === 'levels') {
    const channel = adjustment[levelsChannel] ?? levelsDefault
    const update = (patch: Partial<AdjustmentLevelsChannel>, key: string) => onChange({ [levelsChannel]: { ...channel, ...patch } }, `levels-${levelsChannel}-${key}-${layerId}`)
    return <div className="space-y-2"><select aria-label="Levels channel" value={levelsChannel} onChange={(event) => setLevelsChannel(event.target.value as typeof levelsChannel)} className={fieldClass}><option value="rgb">RGB</option><option value="red">Red</option><option value="green">Green</option><option value="blue">Blue</option></select><RangeControl label="Black input" value={channel.shadowInput} min={0} max={254} onChange={(shadowInput) => update({ shadowInput }, 'black')} onChangeEnd={onChangeEnd} /><RangeControl label="White input" value={channel.highlightInput} min={1} max={255} onChange={(highlightInput) => update({ highlightInput }, 'white')} onChangeEnd={onChangeEnd} /><RangeControl label="Gamma" value={channel.midtoneInput} min={0.1} max={9.99} step={0.01} onChange={(midtoneInput) => update({ midtoneInput }, 'gamma')} onChangeEnd={onChangeEnd} /><RangeControl label="Black output" value={channel.shadowOutput} min={0} max={255} onChange={(shadowOutput) => update({ shadowOutput }, 'output-black')} onChangeEnd={onChangeEnd} /><RangeControl label="White output" value={channel.highlightOutput} min={0} max={255} onChange={(highlightOutput) => update({ highlightOutput }, 'output-white')} onChangeEnd={onChangeEnd} /></div>
  }
  if (adjustment.type === 'exposure') return <><RangeControl label="Exposure" value={adjustment.exposure} min={-5} max={5} step={0.05} onChange={(exposure) => onChange({ exposure }, `exposure-${layerId}`)} onChangeEnd={onChangeEnd} /><RangeControl label="Offset" value={adjustment.offset} min={-0.5} max={0.5} step={0.005} onChange={(offset) => onChange({ offset }, `offset-${layerId}`)} onChangeEnd={onChangeEnd} /><RangeControl label="Gamma" value={adjustment.gamma} min={0.1} max={3} step={0.05} onChange={(gamma) => onChange({ gamma }, `gamma-${layerId}`)} onChangeEnd={onChangeEnd} /></>
  if (adjustment.type === 'vibrance') return <><RangeControl label="Vibrance" value={adjustment.vibrance} min={-100} max={100} suffix="%" onChange={(vibrance) => onChange({ vibrance }, `vibrance-${layerId}`)} onChangeEnd={onChangeEnd} /><RangeControl label="Saturation" value={adjustment.saturation} min={-100} max={100} suffix="%" onChange={(saturation) => onChange({ saturation }, `vibrance-saturation-${layerId}`)} onChangeEnd={onChangeEnd} /></>
  if (adjustment.type === 'selective color') {
    const tone = adjustment[selectiveRange] ?? cmykDefault
    return <div><div className="grid grid-cols-2 gap-2"><select aria-label="Selective color range" value={selectiveRange} onChange={(event) => setSelectiveRange(event.target.value as typeof selectiveRange)} className={fieldClass}>{['reds', 'yellows', 'greens', 'cyans', 'blues', 'magentas', 'whites', 'neutrals', 'blacks'].map((value) => <option key={value} value={value}>{value}</option>)}</select><select aria-label="Selective color mode" value={adjustment.mode} onChange={(event) => onChange({ mode: event.target.value })} className={fieldClass}><option value="relative">Relative</option><option value="absolute">Absolute</option></select></div>{(['c', 'm', 'y', 'k'] as const).map((field) => <RangeControl key={field} label={{ c: 'Cyan', m: 'Magenta', y: 'Yellow', k: 'Black' }[field]} value={tone[field]} min={-100} max={100} suffix="%" onChange={(value) => onChange({ [selectiveRange]: { ...tone, [field]: value } }, `selective-${selectiveRange}-${field}-${layerId}`)} onChangeEnd={onChangeEnd} />)}</div>
  }
  if (adjustment.type === 'channel mixer') {
    const output = adjustment.monochrome ? 'gray' : mixerOutput
    const channel = adjustment[output] ?? (output === 'gray' ? { red: 40, green: 40, blue: 20, constant: 0 } : { ...mixerDefault, [mixerOutput]: 100 })
    return <div><div className="grid grid-cols-2 gap-2"><select aria-label="Channel mixer output" disabled={adjustment.monochrome} value={mixerOutput} onChange={(event) => setMixerOutput(event.target.value as typeof mixerOutput)} className={fieldClass}><option value="red">Red output</option><option value="green">Green output</option><option value="blue">Blue output</option></select><button type="button" aria-pressed={adjustment.monochrome} onClick={() => onChange({ monochrome: !adjustment.monochrome, gray: adjustment.gray ?? { red: 40, green: 40, blue: 20, constant: 0 } })} className={`rounded border text-[9px] ${adjustment.monochrome ? 'border-violet-300/25 bg-violet-300/10 text-violet-200' : 'border-white/[0.08] text-zinc-600'}`}>Monochrome</button></div>{(['red', 'green', 'blue', 'constant'] as const).map((field) => <RangeControl key={field} label={field[0].toUpperCase() + field.slice(1)} value={channel[field]} min={-200} max={200} suffix="%" onChange={(value) => onChange({ [output]: { ...channel, [field]: value } }, `mixer-${output}-${field}-${layerId}`)} onChangeEnd={onChangeEnd} />)}</div>
  }
  if (adjustment.type === 'black & white') return <div>{(['reds', 'yellows', 'greens', 'cyans', 'blues', 'magentas'] as const).map((field) => <RangeControl key={field} label={field[0].toUpperCase() + field.slice(1)} value={adjustment[field]} min={-200} max={300} suffix="%" onChange={(value) => onChange({ [field]: value }, `black-white-${field}-${layerId}`)} onChangeEnd={onChangeEnd} />)}<div className="mt-2 flex items-center gap-2"><button type="button" aria-pressed={adjustment.useTint} onClick={() => onChange({ useTint: !adjustment.useTint })} className={`flex-1 rounded border px-2 py-1.5 text-[9px] ${adjustment.useTint ? 'border-violet-300/25 bg-violet-300/10 text-violet-200' : 'border-white/[0.08] text-zinc-600'}`}>Tint</button>{adjustment.useTint && <input aria-label="Black and white tint" type="color" value={adjustment.tintColor} onChange={(event) => onChange({ tintColor: event.target.value }, `black-white-tint-${layerId}`)} onBlur={onChangeEnd} />}</div></div>
  if (adjustment.type === 'gradient map') {
    const stops = adjustment.colorStops?.length ? adjustment.colorStops : [{ color: '#000000', position: 0, midpoint: 50 }, { color: '#ffffff', position: 1, midpoint: 50 }]
    return <div><div className="flex gap-2">{stops.slice(0, 2).map((stop, index) => <label key={`${stop.position}:${stop.color}`} className="flex flex-1 items-center gap-2 rounded border border-white/[0.07] px-2 py-1 text-[8px] text-zinc-600"><input aria-label={`Gradient map color ${index + 1}`} type="color" value={stop.color} onChange={(event) => onChange({ colorStops: stops.map((candidate, candidateIndex) => candidateIndex === index ? { ...candidate, color: event.target.value } : candidate) }, `gradient-map-${index}-${layerId}`)} onBlur={onChangeEnd} />{index ? 'Highlights' : 'Shadows'}</label>)}</div><button type="button" aria-pressed={adjustment.reverse} onClick={() => onChange({ reverse: !adjustment.reverse })} className={`mt-2 w-full rounded border px-2 py-1.5 text-[9px] ${adjustment.reverse ? 'border-violet-300/25 bg-violet-300/10 text-violet-200' : 'border-white/[0.08] text-zinc-600'}`}>Reverse gradient</button></div>
  }
  if (adjustment.type === 'color lookup') return <div><label className="block cursor-pointer rounded-lg border border-dashed border-white/[0.1] px-3 py-3 text-center text-[9px] text-zinc-500 hover:border-cyan-300/20 hover:text-cyan-100">Load local .cube, .3dl, or .look<input type="file" accept=".cube,.3dl,.look" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; void file.arrayBuffer().then((buffer) => onChange({ lutFormat: file.name.toLowerCase().endsWith('.3dl') ? '3dl' : file.name.toLowerCase().endsWith('.look') ? 'look' : 'cube', lut3DFileName: file.name, lut3DFileData: [...new Uint8Array(buffer)] })).catch(() => undefined) }} /></label>{adjustment.lut3DFileName && <p className="mt-2 truncate text-[9px] text-cyan-100/60">{adjustment.lut3DFileName}</p>}<button type="button" aria-pressed={adjustment.dither} onClick={() => onChange({ dither: !adjustment.dither })} className={`mt-2 w-full rounded border px-2 py-1.5 text-[9px] ${adjustment.dither ? 'border-violet-300/25 bg-violet-300/10 text-violet-200' : 'border-white/[0.08] text-zinc-600'}`}>Dither</button></div>
  if (adjustment.type === 'camera raw') return <div><div className="mb-2 grid grid-cols-3 gap-1">{[['Portrait', { highlights: -18, shadows: 18, texture: -8, clarity: -4, vibrance: 12 }], ['Landscape', { highlights: -12, shadows: 12, texture: 18, clarity: 16, dehaze: 10, vibrance: 18 }], ['Flat', { contrast: -15, highlights: -25, shadows: 25, blacks: 10 }]].map(([name, preset]) => <button key={name as string} type="button" onClick={() => onChange(preset as Record<string, number>)} className="rounded border border-white/[0.07] py-1.5 text-[8px] text-zinc-600 hover:text-zinc-200">{name as string}</button>)}</div>{([
    ['Temperature', 'temperature', -100, 100, 1], ['Tint', 'tint', -100, 100, 1], ['Exposure', 'exposure', -5, 5, 0.05], ['Contrast', 'contrast', -100, 100, 1], ['Highlights', 'highlights', -100, 100, 1], ['Shadows', 'shadows', -100, 100, 1], ['Whites', 'whites', -100, 100, 1], ['Blacks', 'blacks', -100, 100, 1], ['Texture', 'texture', -100, 100, 1], ['Clarity', 'clarity', -100, 100, 1], ['Dehaze', 'dehaze', -100, 100, 1], ['Vibrance', 'vibrance', -100, 100, 1], ['Saturation', 'saturation', -100, 100, 1],
  ] as const).map(([label, field, min, max, step]) => <RangeControl key={field} label={label} value={adjustment[field]} min={min} max={max} step={step} suffix={field === 'exposure' ? undefined : '%'} onChange={(value) => onChange({ [field]: value }, `camera-raw-${field}-${layerId}`)} onChangeEnd={onChangeEnd} />)}</div>
  return null
}
