import { colorSamplerReadout } from '../editor/color-samplers'
import type { DocumentColorSampler } from '../editor/types'
import { ModalDialog } from './ModalDialog'

export function ColorSamplerDialog({ samplers, onChange, onClose }: { samplers: readonly DocumentColorSampler[]; onChange: (samplers: DocumentColorSampler[]) => void; onClose: () => void }) {
  return (
    <ModalDialog label="Color samplers" onDismiss={onClose}>
      <div className="flex min-h-full items-center justify-center p-4"><section className="flex max-h-[min(680px,calc(100dvh-32px))] w-full max-w-2xl flex-col overflow-hidden rounded-2xl border border-white/[0.1] bg-[#17171a] shadow-2xl"><header className="flex items-start justify-between border-b border-white/[0.08] px-5 py-4"><div><h2 className="text-sm font-semibold text-zinc-100">Color samplers</h2><p className="mt-1 text-[10px] text-zinc-600">Shift-click with the Eyedropper to capture persistent composited-color readouts.</p></div><button type="button" aria-label="Close color samplers" onClick={onClose} className="flex size-8 items-center justify-center rounded text-zinc-600 hover:bg-white/[0.05] hover:text-white">×</button></header><div className="min-h-0 flex-1 overflow-auto p-5">{samplers.length ? <div className="space-y-2">{samplers.map((sampler, index) => { const readout = colorSamplerReadout(sampler.color); return <article key={sampler.id} className="grid grid-cols-[auto_1fr_auto] items-center gap-3 rounded-xl border border-white/[0.06] bg-black/15 p-3"><div className="flex size-9 items-center justify-center rounded-lg border border-white/[0.1] font-mono text-[10px] font-bold text-zinc-900" style={{ backgroundColor: sampler.color }}>{index + 1}</div><div><p className="font-mono text-[10px] font-semibold uppercase text-zinc-300">{sampler.color}</p><p className="mt-1 font-mono text-[8px] text-zinc-600">x {sampler.x.toFixed(1)} · y {sampler.y.toFixed(1)}</p><dl className="mt-2 grid grid-cols-3 gap-2 text-[8px]"><div><dt className="text-zinc-700">RGB</dt><dd className="font-mono text-zinc-400">{readout.rgb.join(' ')}</dd></div><div><dt className="text-zinc-700">HSL</dt><dd className="font-mono text-zinc-400">{readout.hsl[0]}° {readout.hsl[1]}% {readout.hsl[2]}%</dd></div><div><dt className="text-zinc-700">CMYK</dt><dd className="font-mono text-zinc-400">{readout.cmyk.join(' ')}</dd></div></dl></div><button type="button" aria-label={`Delete color sampler ${index + 1}`} onClick={() => onChange(samplers.filter((candidate) => candidate.id !== sampler.id))} className="flex size-7 items-center justify-center rounded text-zinc-700 hover:bg-red-400/10 hover:text-red-300">×</button></article> })}</div> : <div className="rounded-xl border border-dashed border-white/[0.07] px-4 py-12 text-center text-[10px] text-zinc-700">No samplers yet. Shift-click a visible pixel with the Eyedropper.</div>}</div><footer className="flex items-center justify-between border-t border-white/[0.07] px-5 py-3"><button type="button" disabled={!samplers.length} onClick={() => onChange([])} className="rounded-lg px-3 py-2 text-[10px] text-zinc-600 hover:bg-red-400/10 hover:text-red-300 disabled:opacity-30">Clear samplers</button><button type="button" onClick={onClose} className="rounded-lg bg-violet-500 px-4 py-2 text-[10px] font-semibold text-white">Done</button></footer></section></div>
    </ModalDialog>
  )
}
