import { useMemo, useState } from 'react'
import type { EditorTool } from './ToolRail'
import { ModalDialog } from './ModalDialog'

const toolHelp: Partial<Record<EditorTool, { summary: string; tips: string[] }>> = {
  move: { summary: 'Position layers and selections on the canvas.', tips: ['Drag the canvas object to move it.', 'Use arrow keys for precise nudges; hold Shift for larger steps.', 'Select multiple layers to align or move them together.'] },
  brush: { summary: 'Paint destructively onto the selected raster layer.', tips: ['Adjust size, hardness, spacing, dynamics, and smoothing in the tool options.', 'Imported ABR and Studio brushes appear in Libraries.', 'Painting respects the active pixel selection and tablet pressure.'] },
  healing: { summary: 'Repair raster areas by blending sampled pixels with the destination.', tips: ['Choose a source point before painting.', 'Use Current & Below to sample the visible composite.', 'Rotation and scale help match texture direction.'] },
  eyedropper: { summary: 'Sample visible canvas colours or capture persistent color-space readouts.', tips: ['Click a visible pixel to update the foreground swatch.', 'Shift-click to add a persistent sampler marker.', 'Open Samplers for RGB, HSL, and CMYK values.'] },
  measure: { summary: 'Measure a heading or calibrated distance, then straighten the document.', tips: ['Drag between two points along the scanned heading.', 'Save lines into the persistent measurement log.', 'Set pixels per unit, rename records, and export the log as CSV.', 'Use Straighten to rotate the selected layer by the measured angle.'] },
  count: { summary: 'Place persistent numbered markers into named count groups.', tips: ['Choose the active group in the options bar.', 'Click the canvas to add a labelled marker.', 'Open Records to rename groups and markers, change group colors, or export CSV.'] },
  note: { summary: 'Attach persistent text annotations to document coordinates.', tips: ['Click the canvas to create and open a note.', 'Edit its title, content, author, color, and popup state.', 'Text annotations round-trip through PSD and PSB files.'] },
  text: { summary: 'Create point type or paragraph text with editable typography.', tips: ['Click for point text or drag a box for paragraph text.', 'Use Properties for OpenType features, variable axes, and text transforms.', 'Load local fonts from File or Libraries.'] },
  pen: { summary: 'Create editable Bézier paths.', tips: ['Click for corner points; drag for smooth handles.', 'Manage saved paths in the Paths panel.', 'Paths can be stroked, filled, converted to selections, or exported.'] },
  crop: { summary: 'Trim the document canvas non-destructively until committed.', tips: ['Drag handles to set the crop bounds.', 'Use the perspective crop tool when scanned edges are not parallel.', 'Commit with Enter or cancel with Escape.'] },
}

const generic = { summary: 'Use this tool directly on the canvas. Its live controls appear above the document.', tips: ['Hover tool icons for their names and shortcuts.', 'Undo is available for committed document and raster changes.', 'Press Command/Ctrl+K to search every command and tool.'] }

export function ContextualHelpDialog({ tool, selectedLayerType, onClose }: { tool: EditorTool; selectedLayerType?: string; onClose: () => void }) {
  const [query, setQuery] = useState('')
  const topics = useMemo(() => [
    { title: 'Active tool', body: toolHelp[tool] ?? generic },
    { title: 'Layers and masks', body: { summary: `The current selection is ${selectedLayerType ? `a ${selectedLayerType} layer` : 'empty'}.`, tips: ['Drag layers and groups to reorder or nest them.', 'Masks preserve editable transparency; disable or unlink them from Properties.', 'Smart objects preserve reusable embedded or linked content.'] } },
    { title: 'Local files and recovery', body: { summary: 'Studio edits locally and autosaves recovery data in this browser.', tips: ['Save a Studio project for a portable copy you control.', 'Recovery snapshots are updated after document changes.', 'Diagnostics omit pixels, names, paths, and resource contents.'] } },
    { title: 'Keyboard and workspace', body: { summary: 'Commands, shortcuts, and panels can be customized.', tips: ['Press Command/Ctrl+K for the command palette.', 'Edit bindings under Edit → Keyboard Shortcuts.', 'Dock, detach, resize, and save panel arrangements as workspaces.'] } },
  ].filter((topic) => `${topic.title} ${topic.body.summary} ${topic.body.tips.join(' ')}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())), [query, selectedLayerType, tool])

  return <ModalDialog label="Contextual help" onDismiss={onClose} className="z-[105] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><section className="flex max-h-[82vh] w-full max-w-2xl flex-col overflow-hidden rounded-2xl border border-white/[0.1] bg-[#17171a] shadow-2xl"><header className="flex items-center justify-between border-b border-white/[0.08] px-5 py-4"><div><h2 className="text-sm font-semibold text-zinc-100">Studio help</h2><p className="mt-1 text-[10px] text-zinc-600">Context for the {tool.replaceAll('-', ' ')} tool and current workspace</p></div><button type="button" onClick={onClose} className="flex size-8 items-center justify-center rounded-lg text-zinc-600 hover:bg-white/[0.06] hover:text-zinc-200">×</button></header><div className="border-b border-white/[0.06] p-3"><input aria-label="Search help" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search help…" className="w-full rounded-lg border border-white/[0.08] bg-black/20 px-3 py-2 text-xs text-zinc-300 outline-none placeholder:text-zinc-700 focus:border-violet-400/40" /></div><div className="min-h-0 flex-1 overflow-y-auto p-4">{topics.map((topic) => <article key={topic.title} className="mb-3 rounded-xl border border-white/[0.07] bg-black/15 p-4"><h3 className="text-[11px] font-semibold text-zinc-300">{topic.title}</h3><p className="mt-1 text-[10px] leading-relaxed text-zinc-500">{topic.body.summary}</p><ul className="mt-3 space-y-1.5">{topic.body.tips.map((tip) => <li key={tip} className="flex gap-2 text-[9px] leading-relaxed text-zinc-600"><span className="text-violet-400/70">•</span>{tip}</li>)}</ul></article>)}{topics.length === 0 && <p className="py-12 text-center text-[11px] text-zinc-700">No matching help topics</p>}</div></section></ModalDialog>
}
