import { useMemo, useState, type KeyboardEvent } from 'react'
import { defaultShortcuts, shortcutCommands, shortcutFromEvent, shortcutLabel, type ShortcutMap } from '../editor/shortcuts'
import { ModalDialog } from './ModalDialog'

export function ShortcutEditor({ value, onChange, onClose }: { value: ShortcutMap; onChange: (value: ShortcutMap) => void; onClose: () => void }) {
  const [query, setQuery] = useState('')
  const filtered = useMemo(() => shortcutCommands.filter((command) => `${command.category} ${command.label}`.toLowerCase().includes(query.toLowerCase())), [query])
  const conflicts = useMemo(() => Object.entries(value).reduce<Record<string, string[]>>((result, [id, binding]) => { if (binding) (result[binding] ??= []).push(id); return result }, {}), [value])
  const capture = (event: KeyboardEvent<HTMLInputElement>, id: string) => {
    event.preventDefault()
    if (event.key === 'Escape') { event.currentTarget.blur(); return }
    if (event.key === 'Backspace' || event.key === 'Delete') { onChange({ ...value, [id]: '' }); return }
    const binding = shortcutFromEvent(event.nativeEvent)
    if (binding) onChange({ ...value, [id]: binding })
  }
  return <ModalDialog label="Keyboard shortcuts" onDismiss={onClose} className="z-[100] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><section className="flex max-h-[82vh] w-full max-w-2xl flex-col overflow-hidden rounded-2xl border border-white/[0.1] bg-[#17171a] shadow-2xl"><header className="flex items-center justify-between border-b border-white/[0.08] px-5 py-4"><div><h2 className="text-sm font-semibold text-zinc-100">Keyboard shortcuts</h2><p className="mt-1 text-[10px] text-zinc-600">Focus a binding and press a key combination. Delete clears it.</p></div><button type="button" onClick={onClose} className="flex size-8 items-center justify-center rounded-lg text-zinc-600 hover:bg-white/[0.06] hover:text-zinc-200">×</button></header><div className="flex items-center gap-2 border-b border-white/[0.06] p-3"><input aria-label="Search shortcuts" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search commands…" className="min-w-0 flex-1 rounded-lg border border-white/[0.08] bg-black/20 px-3 py-2 text-xs text-zinc-300 outline-none placeholder:text-zinc-700 focus:border-violet-400/40" /><button type="button" onClick={() => onChange({ ...defaultShortcuts })} className="rounded-lg border border-white/[0.08] px-3 py-2 text-[10px] text-zinc-500 hover:text-zinc-200">Reset all</button></div><div className="min-h-0 flex-1 overflow-y-auto p-3">{filtered.map((command) => { const binding = value[command.id] ?? ''; const conflict = binding && conflicts[binding]?.length > 1; return <label key={command.id} className="mb-1 grid grid-cols-[90px_1fr_150px] items-center gap-3 rounded-lg px-2 py-1.5 hover:bg-white/[0.03]"><span className="text-[9px] font-semibold tracking-wide text-zinc-700 uppercase">{command.category}</span><span className="text-[11px] text-zinc-400">{command.label}</span><span><input readOnly aria-label={`${command.label} shortcut`} value={shortcutLabel(binding)} onKeyDown={(event) => capture(event, command.id)} className={`w-full rounded-md border bg-black/25 px-2 py-1.5 text-center font-mono text-[10px] outline-none ${conflict ? 'border-amber-400/40 text-amber-200' : 'border-white/[0.08] text-zinc-400 focus:border-violet-400/50'}`} />{conflict && <span className="mt-0.5 block text-center text-[8px] text-amber-400/70">Conflict</span>}</span></label> })}</div><footer className="flex justify-end border-t border-white/[0.07] px-5 py-3"><button type="button" onClick={onClose} className="rounded-lg bg-violet-500 px-4 py-2 text-[10px] font-semibold text-white">Done</button></footer></section></ModalDialog>
}
