import { useState } from 'react'
import type { CustomFontResource } from '../editor/resources'
import type { DocumentPath, LayerPatch, TextLayer } from '../editor/types'
import { numericInputValue } from './input-values'

const fieldClass = 'w-full rounded-md border border-white/[0.08] bg-black/25 px-2 py-1.5 text-[10px] text-zinc-300 outline-none focus:border-violet-400/40'
const openTypeFeatures = [
  ['kern', 'Kerning'], ['liga', 'Ligatures'], ['clig', 'Contextual ligatures'], ['calt', 'Contextual alternates'],
  ['smcp', 'Small caps'], ['onum', 'Oldstyle figures'], ['tnum', 'Tabular figures'], ['frac', 'Fractions'],
] as const

function NumberField({ label, value, min, max, step = 1, onChange, onBlur }: { label: string; value: number; min: number; max: number; step?: number; onChange: (value: number) => void; onBlur?: () => void }) {
  return <label className="text-[8px] text-zinc-600">{label}<input aria-label={label} type="number" min={min} max={max} step={step} value={Math.round(value * 100) / 100} onChange={(event) => onChange(numericInputValue(event.currentTarget, value))} onBlur={onBlur} className={`${fieldClass} mt-1 font-mono`} /></label>
}

export function TextControls({ layer, paths, fonts, update, endHistoryGroup, onLoadFont }: {
  layer: TextLayer
  paths: DocumentPath[]
  fonts: CustomFontResource[]
  update: (patch: LayerPatch, groupKey?: string) => void
  endHistoryGroup: () => void
  onLoadFont: () => void
}) {
  const [panel, setPanel] = useState<'character' | 'paragraph'>('character')
  const [substitutions, setSubstitutions] = useState<Record<string, string>>({})
  const features = layer.openTypeFeatures ?? ['kern', 'liga']
  const axes = { wght: layer.fontWeight, wdth: 100, slnt: layer.fauxItalic ? -12 : 0, opsz: layer.fontSize, ...layer.variableAxes }
  const paragraph = layer.paragraphStyle ?? { firstLineIndent: 0, startIndent: 0, endIndent: 0, spaceBefore: 0, spaceAfter: 0 }
  const setFeature = (feature: string, enabled: boolean) => update({ openTypeFeatures: enabled ? [...new Set([...features, feature])] : features.filter((candidate) => candidate !== feature) })
  const setAxis = (axis: string, value: number) => update({ variableAxes: { ...axes, [axis]: value } }, `text-axis-${layer.id}-${axis}`)
  const setParagraph = (patch: Partial<typeof paragraph>, groupKey?: string) => update({ paragraphStyle: { ...paragraph, ...patch } }, groupKey)

  return <>
    {Boolean(layer.missingFonts?.length) && <section className="mb-3 rounded-lg border border-amber-300/15 bg-amber-300/[0.04] p-2.5"><p className="text-[9px] font-semibold text-amber-100/80">Missing fonts</p><div className="mt-2 space-y-2">{layer.missingFonts!.map((missing) => { const replacement = substitutions[missing] ?? fonts[0]?.family ?? 'Inter'; return <div key={missing} className="grid grid-cols-[1fr_1fr_auto] items-center gap-1"><span className="truncate text-[8px] text-zinc-500" title={missing}>{missing}</span><select aria-label={`Substitute ${missing}`} value={replacement} onChange={(event) => setSubstitutions((current) => ({ ...current, [missing]: event.target.value }))} className={fieldClass}><option value="Inter">Inter</option><option value="Arial">Arial</option><option value="Georgia">Georgia</option>{fonts.map((font) => <option key={font.id} value={font.family}>{font.name}</option>)}</select><button type="button" onClick={() => update({ fontFamily: layer.fontFamily === missing ? replacement : layer.fontFamily, styleRuns: (layer.styleRuns ?? []).map((run) => run.fontFamily === missing ? { ...run, fontFamily: replacement } : run), missingFonts: layer.missingFonts!.filter((font) => font !== missing) })} className="rounded border border-amber-300/15 px-2 py-1.5 text-[8px] text-amber-100/70">Replace</button></div> })}</div></section>}
    <label className="block"><span className="mb-2 block text-[11px] font-medium text-zinc-500">Content</span><textarea className={`${fieldClass} min-h-24 resize-y leading-relaxed`} value={layer.text} onChange={(event) => update({ text: event.target.value }, `text-${layer.id}`)} onBlur={endHistoryGroup} /></label>
    <div className="mt-3 grid grid-cols-2 gap-1 rounded-lg bg-black/30 p-1"><button type="button" aria-pressed={!layer.paragraphBox} onClick={() => update({ paragraphBox: null })} className={`rounded py-2 text-[9px] ${!layer.paragraphBox ? 'bg-violet-400/15 text-violet-100' : 'text-zinc-600'}`}>Point text</button><button type="button" aria-pressed={Boolean(layer.paragraphBox)} onClick={() => update({ paragraphBox: layer.paragraphBox ?? { width: 480, height: 240 } })} className={`rounded py-2 text-[9px] ${layer.paragraphBox ? 'bg-violet-400/15 text-violet-100' : 'text-zinc-600'}`}>Paragraph box</button></div>
    <div className="mt-3 flex gap-2"><select aria-label="Font family" value={layer.fontFamily ?? 'Inter'} onChange={(event) => update({ fontFamily: event.target.value, missingFonts: [] })} className={`${fieldClass} min-w-0 flex-1`}><option value="Inter">Inter</option><option value="Arial">Arial</option><option value="Georgia">Georgia</option><option value="Times New Roman">Times New Roman</option><option value="Courier New">Courier New</option>{fonts.map((font) => <option key={font.id} value={font.family}>{font.name}</option>)}</select><button type="button" onClick={onLoadFont} className="rounded-md border border-white/[0.08] px-2 text-[9px] text-zinc-500 hover:text-zinc-200">Load…</button></div>
    <div className="mt-3 grid grid-cols-2 gap-1 rounded-lg bg-black/30 p-1">{(['character', 'paragraph'] as const).map((value) => <button key={value} type="button" aria-pressed={panel === value} onClick={() => setPanel(value)} className={`rounded py-2 text-[9px] capitalize ${panel === value ? 'bg-white/[0.08] text-zinc-200' : 'text-zinc-600'}`}>{value}</button>)}</div>

    {panel === 'character' && <div className="mt-3 space-y-3">
      <div className="grid grid-cols-2 gap-2"><label className="flex items-center gap-2 rounded-md border border-white/[0.07] p-2 text-[9px] text-zinc-600"><input type="color" value={layer.color} onChange={(event) => update({ color: event.target.value }, `text-color-${layer.id}`)} onBlur={endHistoryGroup} className="size-6" />Colour</label><label className="text-[8px] text-zinc-600">Weight<select aria-label="Font weight" value={layer.fontWeight} onChange={(event) => update({ fontWeight: Number(event.target.value) as 400 | 600 | 700 })} className={`${fieldClass} mt-1`}><option value="400">Regular</option><option value="600">Semibold</option><option value="700">Bold</option></select></label></div>
      <div className="grid grid-cols-2 gap-2"><NumberField label="Size (px)" value={layer.fontSize} min={1} max={1000} onChange={(fontSize) => update({ fontSize }, `font-size-${layer.id}`)} onBlur={endHistoryGroup} /><NumberField label="Leading (px)" value={layer.leading ?? layer.fontSize * 1.18} min={1} max={1500} onChange={(leading) => update({ leading }, `leading-${layer.id}`)} onBlur={endHistoryGroup} /><NumberField label="Tracking (px)" value={layer.letterSpacing} min={-100} max={500} step={0.1} onChange={(letterSpacing) => update({ letterSpacing }, `tracking-${layer.id}`)} onBlur={endHistoryGroup} /><label className="text-[8px] text-zinc-600">Kerning<select aria-label="Kerning" value={layer.kerning ?? 'auto'} onChange={(event) => update({ kerning: event.target.value as TextLayer['kerning'] })} className={`${fieldClass} mt-1`}><option value="auto">Metrics</option><option value="normal">Optical</option><option value="none">None</option></select></label><NumberField label="Baseline shift" value={layer.baselineShift ?? 0} min={-500} max={500} step={0.1} onChange={(baselineShift) => update({ baselineShift }, `baseline-${layer.id}`)} onBlur={endHistoryGroup} /><NumberField label="Horizontal scale %" value={layer.horizontalScale ?? 100} min={10} max={1000} onChange={(horizontalScale) => update({ horizontalScale }, `hscale-${layer.id}`)} onBlur={endHistoryGroup} /><NumberField label="Vertical scale %" value={layer.verticalScale ?? 100} min={10} max={1000} onChange={(verticalScale) => update({ verticalScale }, `vscale-${layer.id}`)} onBlur={endHistoryGroup} /></div>
      <div className="grid grid-cols-3 gap-1">{([['fauxItalic', 'Italic'], ['underline', 'Underline'], ['strikethrough', 'Strike']] as const).map(([key, label]) => <button key={key} type="button" aria-pressed={Boolean(layer[key])} onClick={() => update({ [key]: !layer[key] })} className={`rounded border py-2 text-[8px] ${layer[key] ? 'border-violet-300/25 bg-violet-400/10 text-violet-100' : 'border-white/[0.07] text-zinc-600'}`}>{label}</button>)}</div>
      <section><p className="text-[8px] font-semibold tracking-[0.14em] text-zinc-700 uppercase">OpenType features</p><div className="mt-2 grid grid-cols-2 gap-1">{openTypeFeatures.map(([feature, label]) => <label key={feature} className="flex items-center gap-2 rounded border border-white/[0.06] px-2 py-1.5 text-[8px] text-zinc-600"><input type="checkbox" checked={features.includes(feature)} onChange={(event) => setFeature(feature, event.target.checked)} className="accent-violet-400" />{label}</label>)}</div></section>
      <section><p className="text-[8px] font-semibold tracking-[0.14em] text-zinc-700 uppercase">Variable font axes</p><div className="mt-2 grid grid-cols-2 gap-2"><NumberField label="Weight · wght" value={axes.wght} min={1} max={1000} onChange={(value) => setAxis('wght', value)} onBlur={endHistoryGroup} /><NumberField label="Width · wdth" value={axes.wdth} min={25} max={200} onChange={(value) => setAxis('wdth', value)} onBlur={endHistoryGroup} /><NumberField label="Slant · slnt" value={axes.slnt} min={-90} max={90} onChange={(value) => setAxis('slnt', value)} onBlur={endHistoryGroup} /><NumberField label="Optical · opsz" value={axes.opsz} min={1} max={144} onChange={(value) => setAxis('opsz', value)} onBlur={endHistoryGroup} /></div></section>
      <label className="block text-[8px] text-zinc-600">Fallback stack<input aria-label="Font fallback stack" value={(layer.fallbackFonts ?? []).join(', ')} onChange={(event) => update({ fallbackFonts: event.target.value.split(',').map((value) => value.trim()).filter(Boolean) })} className={`${fieldClass} mt-1`} /></label>
    </div>}

    {panel === 'paragraph' && <div className="mt-3 space-y-3">
      <div className="grid grid-cols-4 gap-1">{(['left', 'center', 'right', 'justify'] as const).map((textAlign) => <button key={textAlign} type="button" aria-pressed={layer.textAlign === textAlign} onClick={() => update({ textAlign })} className={`rounded py-2 text-[8px] capitalize ${layer.textAlign === textAlign ? 'bg-violet-400/15 text-violet-100' : 'bg-white/[0.03] text-zinc-600'}`}>{textAlign}</button>)}</div>
      {layer.paragraphBox && <div className="grid grid-cols-2 gap-2"><NumberField label="Box width" value={layer.paragraphBox.width} min={24} max={10000} onChange={(width) => update({ paragraphBox: { ...layer.paragraphBox!, width } }, `text-box-${layer.id}`)} onBlur={endHistoryGroup} /><NumberField label="Box height" value={layer.paragraphBox.height} min={24} max={10000} onChange={(height) => update({ paragraphBox: { ...layer.paragraphBox!, height } }, `text-box-${layer.id}`)} onBlur={endHistoryGroup} /></div>}
      <div className="grid grid-cols-2 gap-2"><NumberField label="First-line indent" value={paragraph.firstLineIndent} min={-1000} max={1000} onChange={(firstLineIndent) => setParagraph({ firstLineIndent }, `paragraph-${layer.id}`)} onBlur={endHistoryGroup} /><NumberField label="Start indent" value={paragraph.startIndent} min={-1000} max={1000} onChange={(startIndent) => setParagraph({ startIndent }, `paragraph-${layer.id}`)} onBlur={endHistoryGroup} /><NumberField label="End indent" value={paragraph.endIndent} min={-1000} max={1000} onChange={(endIndent) => setParagraph({ endIndent }, `paragraph-${layer.id}`)} onBlur={endHistoryGroup} /><NumberField label="Space before" value={paragraph.spaceBefore} min={0} max={1000} onChange={(spaceBefore) => setParagraph({ spaceBefore }, `paragraph-${layer.id}`)} onBlur={endHistoryGroup} /><NumberField label="Space after" value={paragraph.spaceAfter} min={0} max={1000} onChange={(spaceAfter) => setParagraph({ spaceAfter }, `paragraph-${layer.id}`)} onBlur={endHistoryGroup} /></div>
      <div className="grid grid-cols-2 gap-2"><label className="text-[8px] text-zinc-600">Orientation<select aria-label="Text orientation" value={layer.orientation ?? 'horizontal'} onChange={(event) => update({ orientation: event.target.value as 'horizontal' | 'vertical' })} className={`${fieldClass} mt-1`}><option value="horizontal">Horizontal</option><option value="vertical">Vertical</option></select></label><label className="text-[8px] text-zinc-600">Warp<select aria-label="Text warp style" value={layer.warp?.style ?? 'none'} onChange={(event) => update({ warp: event.target.value === 'none' ? null : { style: event.target.value, value: layer.warp?.value ?? 25, perspective: layer.warp?.perspective ?? 0, perspectiveOther: layer.warp?.perspectiveOther ?? 0, rotate: layer.warp?.rotate ?? 'horizontal' } })} className={`${fieldClass} mt-1`}><option value="none">None</option><option value="arc">Arc</option><option value="arch">Arch</option><option value="bulge">Bulge</option><option value="wave">Wave</option><option value="flag">Flag</option></select></label></div>
      {layer.warp && <div className="grid grid-cols-2 gap-2"><NumberField label="Warp bend %" value={layer.warp.value} min={-100} max={100} onChange={(value) => update({ warp: { ...layer.warp!, value } }, `text-warp-${layer.id}`)} onBlur={endHistoryGroup} /><NumberField label="Perspective %" value={layer.warp.perspective} min={-100} max={100} onChange={(perspective) => update({ warp: { ...layer.warp!, perspective } }, `text-warp-${layer.id}`)} onBlur={endHistoryGroup} /></div>}
      <label className="block text-[8px] text-zinc-600">Text path<select aria-label="Text path" value={layer.textPath?.pathId ?? ''} onChange={(event) => { const selected = paths.find((path) => path.id === event.target.value); update({ textPath: selected?.paths[0] ? { pathId: selected.id, path: structuredClone(selected.paths[0]), offset: 0, flip: false } : null }) }} className={`${fieldClass} mt-1`}><option value="">No path</option>{paths.flatMap((path) => path.paths.length ? [<option key={path.id} value={path.id}>{path.name}</option>] : [])}</select></label>
      {layer.textPath && <div className="grid grid-cols-2 gap-2"><NumberField label="Path offset %" value={layer.textPath.offset} min={-100} max={200} onChange={(offset) => update({ textPath: { ...layer.textPath!, offset } }, `text-path-${layer.id}`)} onBlur={endHistoryGroup} /><button type="button" aria-pressed={layer.textPath.flip} onClick={() => update({ textPath: { ...layer.textPath!, flip: !layer.textPath!.flip } })} className={`mt-3 rounded border text-[8px] ${layer.textPath.flip ? 'border-violet-300/25 bg-violet-400/10 text-violet-100' : 'border-white/[0.07] text-zinc-600'}`}>Flip path side</button></div>}
    </div>}
  </>
}
